#version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Docker/Dockerfile-ui
    ports:
      - "3000:3000"
    environment:
       - CHOKIDAR_USEPOLLING=true
       - REACT_APP_API_URL=http://backend:3001
       - HTTPS=false
      # - FRONTEND_BASE_URL=http://frontend:3000   # in case of Docker used in frontend
     # - PORT=5000   #used in backend to define api port

##CHOKIDAR_USEPOLLING=true tells Chokidar to poll for changes (i.e., check every few milliseconds), ensuring hot reloading works reliably.
#env port will override the configured port ni code
#you can also use .env file  
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Docker/Dockerfile-api
    ports:
      - "3001:3001"
    environment:
       - FRONTEND_BASE_URL=http://frontend:3000
       
