# Use an official Node.js runtime as a parent image
FROM node:22-alpine

# Set the working directory in the container to /var/www/app
WORKDIR /var/www/app

RUN echo "https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
  && apk update \
  && apk add --no-cache ffmpeg

# Copy the package.json and package-lock.json files to the working directory
COPY api/package*.json ./

# Install the app dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the application code to the working directory
COPY api/ .

# Expose the port the app runs on
EXPOSE 9091

# Define the command to start the app
CMD ["node", "index.js"]
