FROM node:22-alpine

WORKDIR /app

#RUN apt-get update && \
#    apt-get install -y ffmpeg
RUN echo "https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
  && apk update \
  && apk add --no-cache ffmpeg

#COPY api/co* ./
#COPY api/*.js ./
#COPY package*.json  ./
COPY api/index.js ./
COPY api/server.js ./
COPY api/corsOptions.js ./
COPY api/package.json ./
COPY api/package-lock.json ./
COPY api/.env ./

RUN npm install

#COPY . .

EXPOSE 3001
#CMD ["npm", "start"]
#CMD [ "npm", "run", "dev" ]
CMD ["node", "index.js"]
